# Generated by Django 3.2.6 on 2021-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian_code', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('email_id', models.CharField(max_length=150)),
            ],
        ),
    ]
