# Generated by Django 3.2.6 on 2021-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
            ],
        ),
    ]
