# Generated by Django 3.2.6 on 2021-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=50)),
                ('pemail', models.CharField(max_length=50)),
                ('pphone', models.CharField(max_length=50)),
                ('ppincode', models.CharField(max_length=50)),
            ],
        ),
    ]
