# Generated by Django 3.2.6 on 2021-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50)),
                ('admno', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
