# Generated by Django 3.2.6 on 2021-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('specilization', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
    ]
