# Generated by Django 3.2.6 on 2021-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('daddress', models.CharField(max_length=50)),
                ('dmobile', models.CharField(max_length=50)),
                ('dspecial', models.CharField(max_length=50)),
                ('demail', models.CharField(max_length=50)),
            ],
        ),
    ]
