# Generated by Django 3.0.3 on 2021-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('admno', models.IntegerField()),
                ('college', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
