# Generated by Django 3.2.6 on 2021-08-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('bauthor', models.CharField(max_length=50)),
                ('bdescp', models.CharField(max_length=100)),
                ('bprice', models.CharField(max_length=50)),
                ('bcategory', models.CharField(max_length=50)),
            ],
        ),
    ]
