# Generated by Django 3.2.6 on 2021-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Email_id', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
    ]
