# Generated by Django 3.2.6 on 2021-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
