# Generated by Django 3.2.6 on 2021-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcode', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ladd', models.CharField(max_length=50)),
                ('lmob', models.CharField(max_length=50)),
                ('lpincode', models.CharField(max_length=50)),
                ('lemail', models.CharField(max_length=50)),
            ],
        ),
    ]
